version: '3'

services:
  
  app:
    build:
      context: "./app"
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000 
    volumes:
      - ./app/api:/src
    environment:
      - ENVIRON
  
  voicevox:
    build:
      context: "./voicevox_engine"
      dockerfile: "Dockerfile"
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'